/**
 * FlowDesk Etsy SEO AI — core AI feature (serverless function)
 *
 * Deploy target: Vercel (or any Node serverless host — Netlify Functions,
 * Cloudflare Pages Functions, etc. with minor export-shape tweaks).
 *
 * What it does: takes a plain-English product description and returns a
 * ready-to-paste Etsy listing kit — SEO title, 13 tags, opening description —
 * generated by a single cheap, fast LLM call (Claude Haiku, kept on the
 * lowest-cost model on purpose, exactly like the existing flowdskai.com tool).
 *
 * Cost target: Haiku-class pricing means even thousands of free-tier
 * generations per month should land comfortably under $5–10 in API spend —
 * near-$0 relative to a $9/mo subscription price.
 *
 * SETUP (the one manual step before this goes live):
 *   1. Get an Anthropic API key from https://console.anthropic.com
 *   2. In your hosting provider's dashboard, add an environment variable:
 *        ANTHROPIC_API_KEY = sk-ant-...
 *   3. Deploy. That's it — no other secrets needed.
 *
 * Until ANTHROPIC_API_KEY is set, this function returns a clear "not
 * configured" error, and the front-end automatically falls back to a local,
 * zero-cost template generator — so the product is fully demoable and usable
 * even before the API key is added.
 */

const SYSTEM_PROMPT = `You are an Etsy SEO copywriting specialist. Given a short product description from a seller, you produce exactly one JSON object (no prose, no markdown fences) with this shape:

{
  "title": "string, <= 140 characters, front-loaded with the highest-intent buyer search phrase, written for Etsy search + human readability",
  "tags": ["array of exactly 13 strings, each <= 20 characters, lowercase, no special characters, ordered from highest to lowest buyer search intent — these are Etsy listing tags"],
  "description": "string, one paragraph (60-90 words), warm and specific, written to hook a browsing buyer in the first two lines and lead naturally into a purchase decision — no generic filler, no emojis, no hashtags"
}

Rules:
- Always return valid JSON and nothing else — no commentary, no markdown code fences.
- Tags must be realistic phrases a buyer would type into Etsy search, not generic single words.
- Never invent specific claims (materials, dimensions, shipping times) the seller did not mention.
- Match the tone to the product category (handmade/craft = warm and personal; templates/digital = practical and benefit-led).`;

/* Simple per-IP rate limiter (resets on cold start — 20 req/min per IP) */
const _rateMap = new Map();
function isRateLimited(ip) {
  const now = Date.now(), window = 60000, limit = 20;
  const e = _rateMap.get(ip) || { n: 0, reset: now + window };
  if (now > e.reset) { e.n = 0; e.reset = now + window; }
  e.n++;
  _rateMap.set(ip, e);
  return e.n > limit;
}

module.exports = async (req, res) => {
  // CORS + method guard
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'method_not_allowed' });

  // Rate limit check
  const clientIp = (req.headers['x-forwarded-for'] || req.socket?.remoteAddress || '').split(',')[0].trim();
  if (isRateLimited(clientIp)) return res.status(429).json({ error: 'rate_limited', message: 'Too many requests — please wait a minute.' });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return res.status(503).json({
      error: 'not_configured',
      message: 'ANTHROPIC_API_KEY is not set on this deployment yet. Add it in your hosting provider environment variables, then redeploy.'
    });
  }

  let keyword = '';
  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    keyword = (body && body.keyword || '').toString().trim().slice(0, 300);
  } catch (e) {
    return res.status(400).json({ error: 'bad_request', message: 'Expected JSON body: { "keyword": "..." }' });
  }
  if (!keyword) return res.status(400).json({ error: 'missing_keyword' });

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 600,
        system: SYSTEM_PROMPT,
        messages: [
          { role: 'user', content: 'Product description from the seller: "' + keyword + '"\n\nReturn the JSON object now.' }
        ]
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      return res.status(502).json({ error: 'upstream_error', message: errText.slice(0, 300) });
    }

    const data = await response.json();
    const raw = (data.content && data.content[0] && data.content[0].text) || '';

    let parsed;
    try {
      const cleaned = raw.trim().replace(/^```(json)?/i, '').replace(/```$/, '').trim();
      parsed = JSON.parse(cleaned);
    } catch (e) {
      return res.status(502).json({ error: 'parse_error', message: 'Model did not return valid JSON.' });
    }

    if (!parsed.title || !Array.isArray(parsed.tags) || !parsed.description) {
      return res.status(502).json({ error: 'shape_error', message: 'Model response missing required fields.' });
    }

    return res.status(200).json({
      title: String(parsed.title).slice(0, 140),
      tags: parsed.tags.slice(0, 13).map(t => String(t).slice(0, 20)),
      description: String(parsed.description)
    });
  } catch (err) {
    return res.status(500).json({ error: 'server_error', message: String(err && err.message || err) });
  }
};
